# Generated by Django 4.2 on 2023-04-15 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0003_role_skill_user_skill_user_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experience",
            old_name="descr",
            new_name="name",
        ),
    ]
