# Generated by Django 4.2 on 2023-04-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0007_user_birth_day_alter_user_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="img",
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
