# Generated by Django 4.2 on 2023-04-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0008_alter_user_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profession",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
