# Generated by Django 4.2 on 2023-04-16 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0014_test_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="descr",
            field=models.CharField(null=True),
        ),
    ]
