# Generated by Django 4.2 on 2023-04-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0015_test_descr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="descr",
            field=models.TextField(null=True),
        ),
    ]
