# Generated by Django 4.2 on 2023-04-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0017_vacancy_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="test_user",
            name="is_passed",
            field=models.BooleanField(default=False),
        ),
    ]
