# Generated by Django 4.2 on 2023-04-16 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0018_test_user_is_passed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Applicant_employer_responce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="API.user"
                    ),
                ),
            ],
        ),
    ]
