# Generated by Django 4.2 on 2023-04-16 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0019_applicant_employer_responce"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant_employer_responce",
            name="vacancy",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="API.vacancy"
            ),
        ),
        migrations.AlterField(
            model_name="applicant_employer_responce",
            name="applicant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Applicant_link",
                to="API.user",
            ),
        ),
    ]
