# Generated by Django 4.2 on 2023-04-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0020_applicant_employer_responce_vacancy_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experience",
            name="user",
        ),
        migrations.AddField(
            model_name="test",
            name="img",
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name="Education",
        ),
        migrations.DeleteModel(
            name="Experience",
        ),
    ]
